[package]
name = "yukinal-terminal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
yukinal-ssh = { workspace = true }

[dev-dependencies]

[lints.rust]
unsafe_code = "forbid"