[package]
name = "yukinal-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[lib]
name = "yukinal_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
yukinal-core = { workspace = true }
yukinal-credentials = { workspace = true }
yukinal-database = { workspace = true }
yukinal-ssh = { workspace = true }
yukinal-terminal = { workspace = true }
