[package]
name = "yukinal-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
yukinal-collector = { workspace = true }
yukinal-database = { workspace = true }
yukinal-ssh = { workspace = true }
yukinal-terminal = { workspace = true }

tracing = { workspace = true }

tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints.rust]
unsafe_code = "forbid"
